### ISSUE TITLE
Training for different image sizes

### ISSUE THREAD

**Issue by PrinceP** [tensorlayer/hyperpose#160]
Procedure for retraining on different image size - 
1. Changed the train_config image size.
2. No change in any other file. 

Gives the following error 
2018-11-22 06:22:58.201844: W tensorflow/core/framework/op_kernel.cc:1261] Invalid argument: ValueError: cannot reshape array of size 240672 into shape (368,656,1)
Traceback (most recent call last):

  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 147, in __call__
    ret = func(*args)

  File "train.py", line 172, in _data_aug_fn
    img_mask = mask_miss.reshape(hin, win, 1)

ValueError: cannot reshape array of size 240672 into shape (368,656,1)

**Comment by elmuz** [comment]
The problem here resides in _tl.prepro.keypoint_resize_random_crop_. Its implementation is not complete and needs to be corrected for non-square resize parameters. If you look at the [code](https://tensorlayer.readthedocs.io/en/stable/_modules/tensorlayer/prepro.html?highlight=keypoint_resize_random_crop) you will understand why.
I see if I can provide a pull request. for that function.

**Comment by elmuz** [comment]
You can check my [PR](https://github.com/tensorlayer/tensorlayer/pull/946) if you want to give it a try..
