### ISSUE TITLE
ValueError: Dimensions must be equal（using userdef dataset）

### ISSUE THREAD

**Issue by lengyuner** [tensorlayer/hyperpose#336]
I am trying to train the model using my own data(fewer keypoints)

I have modified some codes in `hyperpose/model` and `hyperpose/dataset`

but it came out this error:
(happened when running this code)

```
pd_conf, pd_paf, total_loss, re_loss, loss_confs, loss_pafs = \
                    one_step(image.numpy(), gt_conf.numpy(), gt_paf.numpy(), mask.numpy(), train_model)               
```

```
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 606, in _call
    results = self._stateful_fn(*args, **kwds)
  File "C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\eager\function.py", line 2362, in __call__
    graph_function, args, kwargs = self._maybe_define_function(args, kwargs)
  File "C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\eager\function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\eager\function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\eager\def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\eager\function.py", line 3211, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\framework\func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:
    C:\Users\ps\Desktop\djz\hyperpose\hyperpose\Model\openpose\model\openpose.py:55 forward  *
        backbone_features=self.backbone.forward(x)
    C:\Users\ps\Desktop\djz\hyperpose\hyperpose\Model\backbones.py:335 forward  *
        return self.main_block.forward(x)
    C:\Users\envs\Hyperpose\lib\site-packages\tensorlayer\layers\core.py:673 forward  *
        z = layer.forward(z)
    C:\Users\envs\Hyperpose\lib\site-packages\tensorlayer\layers\dense\base_dense.py:106 forward  *
        z = tf.matmul(inputs, self.W)
    C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\util\dispatch.py:180 wrapper
        return target(*args, **kwargs)
    C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\ops\math_ops.py:2798 matmul
        a, b, transpose_a=transpose_a, transpose_b=transpose_b, name=name)
    C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py:5626 mat_mul
        name=name)
    C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\framework\op_def_library.py:742 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\framework\func_graph.py:595 _create_op_internal
        compute_device)
    C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\framework\ops.py:3322 _create_op_internal
        op_def=op_def)
    C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\framework\ops.py:1786 __init__
        control_input_ops)
    C:\Users\envs\Hyperpose\lib\site-packages\tensorflow_core\python\framework\ops.py:1622 _create_c_op
        raise ValueError(str(e))
    ValueError: Dimensions must be equal, but are 86016 and 25088 for 'MatMul' (op: 'MatMul') with input shapes: [4,86016], [25088,4096].
```

**Comment by lengyuner** [comment]
l have sloved this problem. It is caused by the different define of cocopart in different py.
