### ISSUE TITLE
python_demo.py can work, but export_tflite.py and export_pb.py have some problem

### ISSUE THREAD

**Issue by wmy10128** [tensorlayer/HyperPose#398]

**Comment by wmy10128** [comment]
Traceback (most recent call last):
  File "D:\codefiled\py\human_pose\HyperPose-master\export_tflite.py", line 14, in <module>
    model.load_weights(model_weight_path)
  File "D:\Programs\anaconda\envs\hypose\lib\site-packages\tensorlayer\models\core.py", line 958, in load_weights
    utils.load_and_assign_npz(filepath, self)
  File "D:\Programs\anaconda\envs\hypose\lib\site-packages\tensorlayer\files\utils.py", line 2046, in load_and_assign_npz
    assign_weights(weights, network)
  File "D:\Programs\anaconda\envs\hypose\lib\site-packages\tensorlayer\files\utils.py", line 2019, in assign_weights
    ops.append(network.all_weights[i].assign(d[network.all_weights[i].name]))
  File "D:\Programs\anaconda\envs\hypose\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 891, in assign
    (tensor_name, self_shape, value_tensor.shape)
valueError: Cannot assign to variable conv2d_1/filters:0 due to variable shape （3,3,3,32）  and value shape （1,1,384,128）are incompatible.

numpy:1.19.4
tensorflow-gpu:2.4.0
tensorlayer:2.2.3
cuda:11.4

And i download the newest model weights [here](https://drive.google.com/drive/folders/1kFbl7c7DUN19o7Qca3GpcNUjOHjNaCcO)
please help me, thanks
